import { createContext, useContext, useState, useEffect } from 'react';

const LANG_STORAGE_KEY = 'careersearch_lang';

const en = {
  theme: { switchTo: 'Switch theme' },
  nav: {
    home: 'Home',
    jobs: 'Jobs',
    profile: 'Profile',
    messages: 'Messages',
    recruiter: 'Recruiter',
    blog: 'Blog',
    pricing: 'Pricing',
    account: 'Account',
    logout: 'Logout',
    signUp: 'Sign Up',
    login: 'Login',
  },
  common: {
    viewAll: 'View All',
    save: 'Save',
    saved: 'Saved',
    apply: 'Apply',
    edit: 'Edit',
    cancel: 'Cancel',
    viewDetails: 'View Details',
    loginToSave: 'Login to Save',
    jobSaved: 'Job saved!',
    jobRemovedFromSaved: 'Job removed from saved',
  },
  home: {
    aiRecommended: 'AI Recommended Jobs',
    updateProfile: 'Update Your Profile',
    addVideoCv: 'Add a Video CV to stand out to recruiters',
  },
  jobs: {
    filters: 'Filters',
    match: 'match',
    whyFits: 'Why this job fits you',
    search: 'Search',
    industry: 'Industry',
    workType: 'Work Type',
    experience: 'Experience',
    experienceLevel: 'Experience Level',
    sortBy: 'Sort by',
    allIndustries: 'All Industries',
    all: 'All',
    matchSort: 'Match %',
    datePosted: 'Date Posted',
    salary: 'Salary',
    clearFilters: 'Clear Filters',
    jobListings: 'Job Listings',
    jobsFound: 'jobs found',
    loginToApply: 'Login to Apply',
  },
  profile: {
    skills: 'Skills',
    portfolio: 'Portfolio',
    videoCv: 'Video CV (MP4)',
    completeness: 'Profile completeness',
    improveMatch: 'Improve your match score',
    profileBoosted: 'Profile boosted',
    boostProfile: 'Boost Profile',
    personalInfo: 'Personal Info',
    fullName: 'Full Name',
    phone: 'Phone',
    location: 'Location',
    experience: 'Experience',
    hardSkills: 'Hard Skills',
    softSkills: 'Soft Skills',
    addSkillsPlaceholder: 'Type to add skills (autocomplete)',
    education: 'Education',
    certifications: 'Certifications',
    videoCvUploaded: 'Video CV uploaded',
    viewPlay: 'View / Play',
    uploadMp4StandOut: 'Upload MP4 video to stand out to recruiters',
    upgradeForVideo: 'Upgrade to Premium for unlimited video CVs',
    whoViewed: 'Who Viewed Your Profile',
    noProfileViews: 'No profile views yet',
    upgradeToSeeViewers: 'Upgrade to Premium to see who viewed your profile',
    viewProject: 'View project',
    links: 'Links',
    preferences: 'Preferences',
    salary: 'Salary',
    workType: 'Work Type',
    employment: 'Employment',
    preferredCountries: 'Preferred Countries',
  },
  recruiter: {
    dashboard: 'Recruiter Dashboard',
    subscribed: 'Subscribed',
    postNewJob: 'Post New Job',
    totalApplicants: 'Total Applicants',
    activeJobs: 'Active Jobs',
    interviewsScheduled: 'Interviews Scheduled',
    avgTimeToHire: 'Avg. Time to Hire',
    postedJobs: 'Posted Jobs',
    applicants: 'applicants',
    views: 'views',
    filters: 'Filters',
    minMatch: 'Min. Match %',
    experience: 'Experience',
    availability: 'Availability',
    any: 'Any',
    years3: '3+ years',
    years4: '4+ years',
    years5: '5+ years',
    immediate: 'Immediate',
    within2Weeks: 'Within 2 weeks',
    within1Month: 'Within 1 month',
    skillFilter: 'Skill',
    locationFilter: 'Location',
    aiRankedCandidates: 'AI Ranked Candidates',
    name: 'Name',
    match: 'Match',
    skills: 'Skills',
    subscribeToView: 'Subscribe to view',
    quickPreview: 'Quick Candidate Preview',
    viewFullProfile: 'View Full Profile',
    shortlist: 'Shortlist',
    shortlisted: 'Shortlisted',
    inviteToInterview: 'Invite to Interview',
    invited: 'Invited',
    downloadCv: 'Download CV',
    emailCandidate: 'Email Candidate',
    noCandidates: 'No candidates for this job',
    fullProfile: 'Full Profile',
    contact: 'Contact',
    matchScore: 'Match Score',
    summary: 'Summary',
    appliedFor: 'Applied for',
    date: 'Date',
    time: 'Time',
    sendInvite: 'Send Invite',
    postNewJobTitle: 'Post New Job',
    chooseHowToPost: 'Choose how to post your job:',
    featured: 'Featured',
    includedInSub: 'Included in subscription',
    paidPosting: 'Paid Posting',
    paidOneTime: '$49 one-time',
    sponsoredListing: 'Sponsored Listing',
    sponsoredDesc: '$15/day premium placement',
    featuredJobCreated: 'Featured job created',
    removedFromShortlist: 'removed from shortlist',
    addedToShortlist: 'added to shortlist',
    interviewInviteSent: 'Interview invite sent to',
    cvDownloaded: 'CV downloaded',
    topApplicants: 'Top Applicants',
    avgResponseTime: 'Avg. Response Time',
    topMatchScores: 'Top Match Scores',
    analyticsDashboard: 'Analytics Dashboard',
  },
  notifications: {
    title: 'Notifications',
    allCaughtUp: "You're all caught up",
    noNew: 'No new notifications',
  },
  login: {
    welcome: 'Welcome to CareerSearch',
    signIn: 'Sign in to access your account',
    iAm: 'I am a',
    candidate: 'Candidate',
    recruiter: 'Recruiter',
    email: 'Email',
    password: 'Password',
    signInBtn: 'Sign In',
    noAccount: "Don't have an account?",
    invalidCreds: 'Invalid email or password',
    createAccount: 'Create account',
  },
  footer: {
    blog: 'Blog',
    pricing: 'Pricing',
    privacy: 'Privacy Policy',
    terms: 'Terms',
    help: 'Help Center',
    contact: 'Contact',
    copyright: 'Smart Job Match',
  },
  cv: {
    uploadDocuments: 'Upload Documents',
    close: 'Close',
    cvPdf: 'CV (PDF)',
    videoCvMp4: 'Video CV (MP4)',
    uploadPdfMax: 'Upload your CV as a PDF file (max 10MB)',
    uploading: 'Uploading...',
    choosePdf: 'Choose PDF File',
    uploadMp4OrLink: 'Upload MP4 video (recommended) or paste a link (YouTube, Vimeo, etc.)',
    chooseMp4: 'Choose MP4 Video',
    or: 'or',
    pasteVideoUrl: 'Paste video URL (e.g. YouTube, Vimeo)',
    addLink: 'Add Link',
    uploadVideoCv: 'Upload Video CV (MP4)',
    updateProfile: 'Update Your Profile',
    addVideoCvStandOut: 'Add a Video CV to stand out to recruiters',
    uploadCvBetterMatches: 'Upload your CV to get better job matches',
    keepCvUpdated: 'Keep your CV and skills up to date for accurate matching',
    loginToUpdateCv: 'Login to Update CV',
    updateCvVideoCv: 'Update CV / Video CV',
    uploadCv: 'Upload CV',
    errPdfOnly: 'Please upload a PDF file',
    cvUploaded: 'CV uploaded! Skills compatibility updated.',
    errVideoFormat: 'Please upload MP4, WebM, or MOV video',
    errEnterUrl: 'Please enter a video URL',
    errValidUrl: 'Please enter a valid URL',
    videoUploaded: 'Video CV uploaded successfully!',
    videoLinkAdded: 'Video CV link added successfully!',
  },
  trustBadges: {
    platformStandards: 'Platform Standards',
    enterpriseSecurity: 'Enterprise-grade security and reliability',
    gdpr: 'GDPR compliance verified',
    encrypted: 'Encrypted CV & message storage',
    aiMatching: 'AI matching tested with real data',
    mobile: 'Mobile responsiveness tested',
    push: 'Push notifications active',
    multilang: 'Multi-language localization',
    payment: 'Payment system integrated',
    performance: 'Performance load testing completed',
    readMore: 'Read more',
  },
  skills: {
    compatibility: 'Skills Compatibility',
    basedOnProfile: 'Based on your profile and CV',
    uploadToSee: 'Upload your CV to see how your skills match job requirements',
    required: 'Required',
    uploadToAnalyze: 'Upload your CV to analyze your skills compatibility',
    profileStrength: 'Profile Strength',
    addSkill: 'Add skill...',
  },
  jobDetails: {
    description: 'Description',
    requirements: 'Requirements',
    benefits: 'Benefits',
    jobNotFound: 'Job not found.',
    backToJobs: 'Back to Jobs',
    featured: 'Featured',
    sponsored: 'Sponsored',
    jobDescription: 'Job Description',
    requiredSkills: 'Required Skills',
    experience: 'Experience',
    posted: 'Posted',
    deadline: 'Deadline',
    whyFits: 'Why this job fits you',
    advancedAi: 'Advanced AI Insights',
    advancedAiPremium: 'Advanced AI Insights (Premium)',
    skillGap: 'Skill gap',
    salaryBenchmark: 'Salary benchmark',
    interviewLikelihood: 'Interview likelihood',
    competition: 'Competition',
    loginToApply: 'Login to Apply',
    saveJob: 'Save Job',
  },
  requireLogin: {
    title: 'Login Required',
    signInToAccess: 'Please sign in to access this page',
    signIn: 'Sign In',
  },
  pricing: {
    title: 'Smart Job Match',
    tagline: 'AI-powered career matching for candidates and recruiters',
    ourPlatform: 'Our Platform',
    subscriptionPlans: 'Subscription Plans',
    forCandidates: 'For Candidates',
    forRecruiters: 'For Recruiters',
    premium: 'Premium',
    monthlySub: 'Monthly Subscription',
    accelerateSearch: 'Accelerate your job search with advanced tools',
    findTalent: 'Find the best talent faster',
    upgradePremium: 'Upgrade to Premium',
    getRecruiterAccess: 'Get Recruiter Access',
    additionalRevenue: 'Additional Revenue Options',
    learnMore: 'Learn more',
    try: 'Try',
  },
  messages: {
    conversations: 'Conversations',
    scheduleMeeting: 'Schedule Meeting',
    typeMessage: 'Type a message...',
    send: 'Send',
    attach: 'Attach',
    attachFile: 'Attach file',
    selectConversation: 'Select a conversation to start messaging',
    sendMessagesShare: 'Send messages, share files, and schedule meetings',
    date: 'Date',
    time: 'Time',
    cancel: 'Cancel',
    schedule: 'Schedule',
  },
  contact: {
    backToHome: 'Back to Home',
    contactUs: 'Contact Us',
    getInTouch: "We'd love to hear from you. Get in touch with our team.",
    sendMessage: 'Send a Message',
    thankYou: "Thank you for your message! We'll get back to you within 24–48 hours.",
    sendAnother: 'Send another message',
    name: 'Name',
    email: 'Email',
    category: 'Category',
    subject: 'Subject',
    message: 'Message',
    yourName: 'Your name',
    briefSubject: 'Brief subject',
    howCanWeHelp: 'How can we help?',
    sendMsg: 'Send Message',
    generalInquiry: 'General Inquiry',
    technicalSupport: 'Technical Support',
    billing: 'Billing',
    recruiterSupport: 'Recruiter Support',
    partnership: 'Partnership',
    supportHours: 'Support Hours',
    recruiters: 'Recruiters',
    privacyLegal: 'Privacy & Legal',
    office: 'Office',
  },
  signup: {
    createAccount: 'Create Account',
    joinTagline: 'Join CareerSearch to find your dream job',
    iAm: 'I am a',
    jobSeeker: 'Job Seeker',
    recruiter: 'Recruiter',
    companyName: 'Company Name',
    fullName: 'Full Name',
    yourCompany: 'Your company',
    yourName: 'Your name',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    min6Chars: 'Min. 6 characters',
    confirmYourPassword: 'Confirm your password',
    createAccountBtn: 'Create Account',
    alreadyHave: 'Already have an account?',
    signIn: 'Sign in',
    errPasswordsMatch: 'Passwords do not match',
    errPasswordLength: 'Password must be at least 6 characters',
    errSignUpFailed: 'Sign up failed',
  },
  account: {
    settings: 'Settings',
    personalData: 'Personal Data',
    emailPreferences: 'Email Preferences',
    passwordSecurity: 'Password & Security',
    privacyControls: 'Privacy Controls',
    subscriptionPlan: 'Subscription Plan',
    deleteAccount: 'Delete Account',
    managePersonalInfo: 'Manage your personal information',
    chooseEmails: 'Choose what emails you receive',
    managePassword: 'Manage your password and security settings',
    controlVisibility: 'Control who can see your profile',
    manageSubscription: 'Manage your subscription',
    saveChanges: 'Save Changes',
    savePreferences: 'Save Preferences',
    updatePassword: 'Update Password',
    savePrivacySettings: 'Save Privacy Settings',
    newMatchingJobs: 'New matching jobs',
    applicationStatus: 'Application status updates',
    recruiterMessages: 'Recruiter messages',
    interviewInvitations: 'Interview invitations',
    weeklyDigest: 'Weekly job digest',
    productUpdates: 'Product updates & tips',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    enterCurrentPassword: 'Enter current password',
    enterNewPassword: 'Enter new password',
    confirmNewPasswordPlaceholder: 'Confirm new password',
    twoFactor: 'Two-factor authentication',
    loginNotifications: 'Login notifications',
    public: 'Public',
    publicDesc: 'Your profile is visible to all recruiters',
    private: 'Private',
    privateDesc: 'Only visible when you apply to jobs',
    showInSearch: 'Show profile in search results',
    allowContact: 'Allow recruiters to contact me',
    premium: 'Premium',
    free: 'Free',
    careerSearchPremium: 'CareerSearch Premium',
    careerSearchFree: 'CareerSearch Free',
    premiumFeatures: 'Advanced AI insights, unlimited video CV, profile viewers, profile boost',
    freeFeatures: 'Basic job matching and profile visibility',
    cancelPremium: 'Cancel Premium',
    upgradeToPremium: 'Upgrade to Premium',
    upTo5Applications: 'Up to 5 job applications per month',
    basicVisibility: 'Basic profile visibility',
    emailNotifs: 'Email notifications',
    subscribed: 'Subscribed',
    recruiterMonthly: 'Recruiter Monthly',
    recruiterFree: 'Recruiter Free',
    recruiterPremiumFeatures: 'AI filtering, unlimited candidate access, featured job posts',
    limitedAccess: 'Limited candidate access',
    cancelSubscription: 'Cancel Subscription',
    subscribeRecruiter: 'Subscribe — Recruiter Monthly',
    upTo10Views: 'Up to 10 candidate views per job',
    basicPosting: 'Basic job posting',
    premiumForCandidates: 'Premium — For Candidates',
    recruiterFeatures: 'Recruiter Monthly — Features',
    deleteDesc: 'Permanently delete your account and all associated data. This action cannot be undone.',
    deleteWarning: 'You will lose access to your profile, applications, and messages.',
    deleteMyAccount: 'Delete My Account',
    typeDeleteToConfirm: 'Type DELETE to confirm:',
    typeDelete: 'Type DELETE',
    deleteAccountBtn: 'Delete Account',
  },
  legal: {
    backToHome: 'Back to Home',
    privacyTitle: 'Privacy Policy',
    termsTitle: 'Terms of Service',
    helpTitle: 'Help Center',
    lastUpdated: 'Last updated',
  },
  help: {
    findAnswers: 'Find answers to common questions',
    searchPlaceholder: 'Search for help...',
    all: 'All',
    noResults: 'No results found. Try a different search or',
    contactUs: 'contact us',
    stillNeedHelp: 'Still need help?',
    supportHere: 'Our support team is here for you.',
    contactSupport: 'Contact Support',
  },
  placeholder: {
    comingSoon: 'This page is coming soon.',
    page: 'Page',
  },
  blog: {
    backToBlog: 'Back to Blog',
    backToHome: 'Back to Home',
    blogNews: 'Blog & News',
    tagline: 'Career insights, industry trends, and tips to advance your job search',
    readMore: 'Read more',
    resources: 'Resources',
    browseJobs: 'Browse Jobs',
    helpCenter: 'Help Center',
    contactUs: 'Contact Us',
    platformStandards: 'Platform Standards',
    newsletter: 'Newsletter',
    newsletterDesc: 'Get career tips, job market insights, and platform updates delivered to your inbox.',
    subscribed: "You're subscribed! Check your inbox for our next update.",
    alreadySubscribed: 'This email is already subscribed. Thanks for being with us!',
    somethingWrong: 'Something went wrong. Please try again.',
    tryAgain: 'Try again',
    enterEmail: 'Enter your email',
    subscribe: 'Subscribe',
  },
};

const translations = {
  en,
  es: {
    theme: { switchTo: 'Cambiar tema' },
    nav: {
      home: 'Inicio',
      jobs: 'Empleos',
      profile: 'Perfil',
      messages: 'Mensajes',
      recruiter: 'Reclutador',
      blog: 'Blog',
      pricing: 'Precios',
      account: 'Cuenta',
      logout: 'Cerrar sesión',
      signUp: 'Registrarse',
      login: 'Iniciar sesión',
    },
    common: {
      viewAll: 'Ver todo',
      save: 'Guardar',
      saved: 'Guardado',
      apply: 'Aplicar',
      edit: 'Editar',
      cancel: 'Cancelar',
      viewDetails: 'Ver detalles',
      loginToSave: 'Iniciar sesión para guardar',
      jobSaved: '¡Empleo guardado!',
      jobRemovedFromSaved: 'Empleo eliminado de guardados',
    },
    home: { aiRecommended: 'Empleos recomendados por IA', updateProfile: 'Actualiza tu perfil', addVideoCv: 'Añade un CV en video' },
    jobs: { filters: 'Filtros', match: 'coincidencia', whyFits: 'Por qué te conviene', search: 'Buscar', industry: 'Industria', workType: 'Tipo', experience: 'Experiencia', sortBy: 'Ordenar' },
    profile: { skills: 'Habilidades', portfolio: 'Portafolio', videoCv: 'CV en video (MP4)', completeness: 'Completitud del perfil', improveMatch: 'Mejora tu puntuación', personalInfo: 'Información personal', fullName: 'Nombre completo', phone: 'Teléfono', location: 'Ubicación', experience: 'Experiencia', education: 'Educación', certifications: 'Certificaciones', preferences: 'Preferencias', salary: 'Salario', workType: 'Tipo de trabajo', employment: 'Empleo', preferredCountries: 'Países preferidos' },
    recruiter: { dashboard: 'Panel de reclutador', subscribed: 'Suscrito', postNewJob: 'Publicar empleo', totalApplicants: 'Total solicitantes', activeJobs: 'Empleos activos', interviewsScheduled: 'Entrevistas programadas', avgTimeToHire: 'Tiempo medio de contratación', postedJobs: 'Empleos publicados', applicants: 'solicitantes', views: 'vistas', filters: 'Filtros', minMatch: 'Coincidencia mín. %', experience: 'Experiencia', availability: 'Disponibilidad', any: 'Cualquiera', aiRankedCandidates: 'Candidatos clasificados por IA', name: 'Nombre', match: 'Coincidencia', skills: 'Habilidades', subscribeToView: 'Suscríbete para ver', quickPreview: 'Vista previa rápida', viewFullProfile: 'Ver perfil completo', shortlist: 'Lista corta', shortlisted: 'En lista', inviteToInterview: 'Invitar a entrevista', invited: 'Invitado', downloadCv: 'Descargar CV', emailCandidate: 'Enviar email', noCandidates: 'Sin candidatos para este empleo', contact: 'Contacto', matchScore: 'Puntuación', summary: 'Resumen', appliedFor: 'Solicitó', date: 'Fecha', time: 'Hora', sendInvite: 'Enviar invitación', analyticsDashboard: 'Panel de análisis' },
    notifications: { title: 'Notificaciones', allCaughtUp: 'Estás al día', noNew: 'Sin notificaciones nuevas' },
    login: { welcome: 'Bienvenido a CareerSearch', signIn: 'Inicia sesión para acceder', iAm: 'Soy', candidate: 'Candidato', recruiter: 'Reclutador', email: 'Correo', password: 'Contraseña', signInBtn: 'Iniciar sesión', noAccount: '¿No tienes cuenta?', invalidCreds: 'Correo o contraseña incorrectos', createAccount: 'Crear cuenta' },
    footer: { blog: 'Blog', pricing: 'Precios', privacy: 'Privacidad', terms: 'Términos', help: 'Ayuda', contact: 'Contacto', copyright: 'Smart Job Match' },
    cv: { uploadDocuments: 'Subir documentos', close: 'Cerrar', cvPdf: 'CV (PDF)', videoCvMp4: 'CV en video (MP4)', uploadPdfMax: 'Sube tu CV en PDF (máx. 10MB)', uploading: 'Subiendo...', choosePdf: 'Elegir archivo PDF', uploadMp4OrLink: 'Sube video MP4 o pega un enlace (YouTube, Vimeo)', chooseMp4: 'Elegir video MP4', or: 'o', pasteVideoUrl: 'Pega URL del video', addLink: 'Añadir enlace', uploadVideoCv: 'Subir CV en video (MP4)', updateProfile: 'Actualiza tu perfil', addVideoCvStandOut: 'Añade un CV en video para destacar', uploadCvBetterMatches: 'Sube tu CV para mejores coincidencias', keepCvUpdated: 'Mantén tu CV actualizado', loginToUpdateCv: 'Iniciar sesión para actualizar', updateCvVideoCv: 'Actualizar CV / CV en video', uploadCv: 'Subir CV', errPdfOnly: 'Sube un archivo PDF', cvUploaded: '¡CV subido!', errVideoFormat: 'Sube video MP4, WebM o MOV', errEnterUrl: 'Introduce una URL', errValidUrl: 'Introduce una URL válida', videoUploaded: '¡CV en video subido!', videoLinkAdded: '¡Enlace añadido!' },
    trustBadges: { platformStandards: 'Estándares de la plataforma', enterpriseSecurity: 'Seguridad empresarial', gdpr: 'GDPR verificado', encrypted: 'CV y mensajes cifrados', aiMatching: 'IA probada', mobile: 'Diseño móvil', push: 'Notificaciones activas', multilang: 'Multiidioma', payment: 'Pagos integrados', performance: 'Rendimiento probado', readMore: 'Leer más' },
    skills: { compatibility: 'Compatibilidad de habilidades', basedOnProfile: 'Según tu perfil y CV', uploadToSee: 'Sube tu CV para ver coincidencias', required: 'Requerido', uploadToAnalyze: 'Sube tu CV para analizar', profileStrength: 'Fortaleza del perfil', addSkill: 'Añadir habilidad...' },
    jobDetails: { description: 'Descripción', requirements: 'Requisitos', benefits: 'Beneficios', jobNotFound: 'Empleo no encontrado.', backToJobs: 'Volver a empleos', featured: 'Destacado', sponsored: 'Patrocinado', jobDescription: 'Descripción', requiredSkills: 'Habilidades requeridas', experience: 'Experiencia', posted: 'Publicado', deadline: 'Fecha límite', whyFits: 'Por qué te conviene', advancedAi: 'Análisis IA avanzado', advancedAiPremium: 'Análisis IA (Premium)', skillGap: 'Brecha de habilidades', salaryBenchmark: 'Salario de referencia', interviewLikelihood: 'Probabilidad de entrevista', competition: 'Competencia', loginToApply: 'Iniciar sesión para aplicar', saveJob: 'Guardar empleo' },
    requireLogin: { title: 'Inicio de sesión requerido', signInToAccess: 'Inicia sesión para acceder', signIn: 'Iniciar sesión' },
    pricing: { title: 'Smart Job Match', tagline: 'Emparejamiento de carreras con IA para candidatos y reclutadores', ourPlatform: 'Nuestra plataforma', subscriptionPlans: 'Planes de suscripción', forCandidates: 'Para candidatos', forRecruiters: 'Para reclutadores', premium: 'Premium', monthlySub: 'Suscripción mensual', accelerateSearch: 'Acelera tu búsqueda de empleo', findTalent: 'Encuentra el mejor talento más rápido', upgradePremium: 'Actualizar a Premium', getRecruiterAccess: 'Acceso reclutador', additionalRevenue: 'Opciones de ingresos adicionales', learnMore: 'Saber más', try: 'Probar' },
    messages: { conversations: 'Conversaciones', scheduleMeeting: 'Programar reunión', typeMessage: 'Escribe un mensaje...', send: 'Enviar', attach: 'Adjuntar', attachFile: 'Adjuntar archivo', selectConversation: 'Selecciona una conversación para empezar', sendMessagesShare: 'Envía mensajes, comparte archivos y programa reuniones', date: 'Fecha', time: 'Hora', cancel: 'Cancelar', schedule: 'Programar' },
    contact: { backToHome: 'Volver al inicio', contactUs: 'Contáctanos', getInTouch: 'Nos encantaría saber de ti.', sendMessage: 'Enviar mensaje', thankYou: '¡Gracias! Te responderemos en 24-48 horas.', sendAnother: 'Enviar otro mensaje', name: 'Nombre', email: 'Correo', category: 'Categoría', subject: 'Asunto', message: 'Mensaje', yourName: 'Tu nombre', briefSubject: 'Asunto breve', howCanWeHelp: '¿Cómo podemos ayudarte?', sendMsg: 'Enviar mensaje', generalInquiry: 'Consulta general', technicalSupport: 'Soporte técnico', billing: 'Facturación', recruiterSupport: 'Soporte reclutadores', partnership: 'Asociación', supportHours: 'Horario de soporte', recruiters: 'Reclutadores', privacyLegal: 'Privacidad y legal', office: 'Oficina' },
    signup: { createAccount: 'Crear cuenta', joinTagline: 'Únete a CareerSearch para encontrar tu trabajo ideal', iAm: 'Soy', jobSeeker: 'Buscador de empleo', recruiter: 'Reclutador', companyName: 'Nombre de empresa', fullName: 'Nombre completo', yourCompany: 'Tu empresa', yourName: 'Tu nombre', password: 'Contraseña', confirmPassword: 'Confirmar contraseña', min6Chars: 'Mín. 6 caracteres', confirmYourPassword: 'Confirma tu contraseña', createAccountBtn: 'Crear cuenta', alreadyHave: '¿Ya tienes cuenta?', signIn: 'Iniciar sesión', errPasswordsMatch: 'Las contraseñas no coinciden', errPasswordLength: 'La contraseña debe tener al menos 6 caracteres', errSignUpFailed: 'Error al registrarse' },
    account: { settings: 'Configuración', personalData: 'Datos personales', emailPreferences: 'Preferencias de correo', passwordSecurity: 'Contraseña y seguridad', privacyControls: 'Privacidad', subscriptionPlan: 'Plan de suscripción', deleteAccount: 'Eliminar cuenta', managePersonalInfo: 'Gestiona tu información personal', chooseEmails: 'Elige qué correos recibir', managePassword: 'Gestiona tu contraseña y seguridad', controlVisibility: 'Controla quién ve tu perfil', manageSubscription: 'Gestiona tu suscripción', saveChanges: 'Guardar cambios', savePreferences: 'Guardar preferencias', updatePassword: 'Actualizar contraseña', savePrivacySettings: 'Guardar privacidad', newMatchingJobs: 'Nuevos empleos que coinciden', applicationStatus: 'Estado de solicitudes', recruiterMessages: 'Mensajes de reclutadores', interviewInvitations: 'Invitaciones a entrevistas', weeklyDigest: 'Resumen semanal', productUpdates: 'Actualizaciones y consejos', currentPassword: 'Contraseña actual', newPassword: 'Nueva contraseña', confirmNewPassword: 'Confirmar nueva contraseña', enterCurrentPassword: 'Introduce la contraseña actual', enterNewPassword: 'Introduce la nueva contraseña', confirmNewPasswordPlaceholder: 'Confirma la nueva contraseña', twoFactor: 'Autenticación en dos pasos', loginNotifications: 'Notificaciones de inicio de sesión', public: 'Público', publicDesc: 'Tu perfil es visible para todos los reclutadores', private: 'Privado', privateDesc: 'Solo visible cuando aplicas a empleos', showInSearch: 'Mostrar perfil en búsquedas', allowContact: 'Permitir que reclutadores me contacten', premium: 'Premium', free: 'Gratis', careerSearchPremium: 'CareerSearch Premium', careerSearchFree: 'CareerSearch Gratis', premiumFeatures: 'Análisis IA, CV en video ilimitado, visitantes del perfil, impulso', freeFeatures: 'Emparejamiento básico y visibilidad', cancelPremium: 'Cancelar Premium', upgradeToPremium: 'Actualizar a Premium', upTo5Applications: 'Hasta 5 solicitudes al mes', basicVisibility: 'Visibilidad básica', emailNotifs: 'Notificaciones por correo', subscribed: 'Suscrito', recruiterMonthly: 'Reclutador mensual', recruiterFree: 'Reclutador gratis', recruiterPremiumFeatures: 'Filtros IA, acceso ilimitado a candidatos, publicaciones destacadas', limitedAccess: 'Acceso limitado a candidatos', cancelSubscription: 'Cancelar suscripción', subscribeRecruiter: 'Suscribirse — Reclutador mensual', upTo10Views: 'Hasta 10 vistas de candidatos por empleo', basicPosting: 'Publicación básica', premiumForCandidates: 'Premium — Para candidatos', recruiterFeatures: 'Reclutador mensual — Características', deleteDesc: 'Eliminar permanentemente tu cuenta y datos. Esta acción no se puede deshacer.', deleteWarning: 'Perderás acceso a tu perfil, solicitudes y mensajes.', deleteMyAccount: 'Eliminar mi cuenta', typeDeleteToConfirm: 'Escribe DELETE para confirmar:', typeDelete: 'Escribe DELETE', deleteAccountBtn: 'Eliminar cuenta' },
    blog: { backToBlog: 'Volver al blog', backToHome: 'Volver al inicio', blogNews: 'Blog y noticias', tagline: 'Consejos de carrera, tendencias y búsqueda de empleo', readMore: 'Leer más', resources: 'Recursos', browseJobs: 'Ver empleos', helpCenter: 'Centro de ayuda', contactUs: 'Contáctanos', platformStandards: 'Estándares de la plataforma', newsletter: 'Boletín', newsletterDesc: 'Recibe consejos, tendencias y actualizaciones en tu correo.', subscribed: '¡Suscrito! Revisa tu bandeja.', alreadySubscribed: 'Este correo ya está suscrito. ¡Gracias!', somethingWrong: 'Algo salió mal. Intenta de nuevo.', tryAgain: 'Intentar de nuevo', enterEmail: 'Introduce tu correo', subscribe: 'Suscribirse' },
    legal: { backToHome: 'Volver al inicio', privacyTitle: 'Política de privacidad', termsTitle: 'Términos de servicio', helpTitle: 'Centro de ayuda', lastUpdated: 'Última actualización' },
    help: { findAnswers: 'Encuentra respuestas a preguntas frecuentes', searchPlaceholder: 'Buscar ayuda...', all: 'Todo', noResults: 'No hay resultados. Prueba otra búsqueda o', contactUs: 'contáctanos', stillNeedHelp: '¿Necesitas más ayuda?', supportHere: 'Nuestro equipo está aquí.', contactSupport: 'Contactar soporte' },
    placeholder: { comingSoon: 'Esta página estará disponible pronto.', page: 'Página' },
  },
  fr: {
    theme: { switchTo: 'Changer le thème' },
    nav: {
      home: 'Accueil',
      jobs: 'Emplois',
      profile: 'Profil',
      messages: 'Messages',
      recruiter: 'Recruteur',
      blog: 'Blog',
      pricing: 'Tarifs',
      account: 'Compte',
      logout: 'Déconnexion',
      signUp: "S'inscrire",
      login: 'Connexion',
    },
    common: {
      viewAll: 'Voir tout',
      save: 'Enregistrer',
      saved: 'Enregistré',
      apply: 'Postuler',
      edit: 'Modifier',
      cancel: 'Annuler',
      viewDetails: 'Voir les détails',
      loginToSave: 'Connexion pour enregistrer',
      jobSaved: 'Emploi enregistré !',
      jobRemovedFromSaved: 'Emploi retiré des favoris',
    },
    home: { aiRecommended: 'Emplois recommandés par IA', updateProfile: 'Mettez à jour votre profil', addVideoCv: 'Ajoutez une vidéo CV' },
    jobs: { filters: 'Filtres', match: 'correspondance', whyFits: 'Pourquoi ce poste vous convient', search: 'Rechercher', industry: 'Secteur', workType: 'Type', experience: 'Expérience', sortBy: 'Trier' },
    profile: { skills: 'Compétences', portfolio: 'Portfolio', videoCv: 'CV vidéo (MP4)' },
    notifications: { title: 'Notifications', allCaughtUp: "Vous êtes à jour", noNew: 'Aucune nouvelle notification' },
    login: { welcome: 'Bienvenue sur CareerSearch', signIn: 'Connectez-vous pour accéder', iAm: 'Je suis', candidate: 'Candidat', recruiter: 'Recruteur', email: 'E-mail', password: 'Mot de passe', signInBtn: 'Connexion', noAccount: "Pas de compte ?", invalidCreds: 'E-mail ou mot de passe incorrect', createAccount: 'Créer un compte' },
    footer: { blog: 'Blog', pricing: 'Tarifs', privacy: 'Confidentialité', terms: 'Conditions', help: 'Aide', contact: 'Contact', copyright: 'Smart Job Match' },
    cv: { uploadDocuments: 'Télécharger des documents', close: 'Fermer', cvPdf: 'CV (PDF)', videoCvMp4: 'CV vidéo (MP4)', uploadPdfMax: 'Téléchargez votre CV en PDF (max 10 Mo)', uploading: 'Téléchargement...', choosePdf: 'Choisir un PDF', uploadMp4OrLink: 'Téléchargez une vidéo MP4 ou collez un lien', chooseMp4: 'Choisir une vidéo MP4', or: 'ou', pasteVideoUrl: 'Collez l\'URL de la vidéo', addLink: 'Ajouter le lien', uploadVideoCv: 'Télécharger CV vidéo (MP4)', updateProfile: 'Mettez à jour votre profil', addVideoCvStandOut: 'Ajoutez une vidéo CV pour vous démarquer', uploadCvBetterMatches: 'Téléchargez votre CV pour de meilleures correspondances', keepCvUpdated: 'Gardez votre CV à jour', loginToUpdateCv: 'Connexion pour mettre à jour', updateCvVideoCv: 'Mettre à jour CV / CV vidéo', uploadCv: 'Télécharger CV', errPdfOnly: 'Veuillez télécharger un PDF', cvUploaded: 'CV téléchargé !', errVideoFormat: 'Veuillez télécharger une vidéo MP4, WebM ou MOV', errEnterUrl: 'Veuillez entrer une URL', errValidUrl: 'Veuillez entrer une URL valide', videoUploaded: 'CV vidéo téléchargé !', videoLinkAdded: 'Lien ajouté !' },
    trustBadges: { platformStandards: 'Normes de la plateforme', enterpriseSecurity: 'Sécurité et fiabilité', gdpr: 'Conformité RGPD', encrypted: 'CV et messages chiffrés', aiMatching: 'IA testée', mobile: 'Mobile testé', push: 'Notifications actives', multilang: 'Multilingue', payment: 'Paiements intégrés', performance: 'Performance testée', readMore: 'Lire la suite' },
    skills: { compatibility: 'Compatibilité des compétences', basedOnProfile: 'Basé sur votre profil', uploadToSee: 'Téléchargez votre CV pour voir les correspondances', required: 'Requis', uploadToAnalyze: 'Téléchargez votre CV pour analyser', profileStrength: 'Force du profil', addSkill: 'Ajouter une compétence...' },
    jobDetails: { description: 'Description', requirements: 'Exigences', benefits: 'Avantages', jobNotFound: 'Emploi introuvable.', backToJobs: 'Retour aux emplois', featured: 'En vedette', sponsored: 'Sponsorisé', jobDescription: 'Description', requiredSkills: 'Compétences requises', experience: 'Expérience', posted: 'Publié', deadline: 'Date limite', whyFits: 'Pourquoi ce poste vous convient', advancedAi: 'Analyse IA avancée', advancedAiPremium: 'Analyse IA (Premium)', skillGap: 'Écart de compétences', salaryBenchmark: 'Salaire de référence', interviewLikelihood: 'Probabilité d\'entretien', competition: 'Concurrence', loginToApply: 'Connexion pour postuler', saveJob: 'Enregistrer' },
    requireLogin: { title: 'Connexion requise', signInToAccess: 'Connectez-vous pour accéder', signIn: 'Connexion' },
  },
  de: {
    theme: { switchTo: 'Design wechseln' },
    nav: {
      home: 'Start',
      jobs: 'Jobs',
      profile: 'Profil',
      messages: 'Nachrichten',
      recruiter: 'Personalvermittler',
      blog: 'Blog',
      pricing: 'Preise',
      account: 'Konto',
      logout: 'Abmelden',
      signUp: 'Registrieren',
      login: 'Anmelden',
    },
    common: {
      viewAll: 'Alle anzeigen',
      save: 'Speichern',
      saved: 'Gespeichert',
      apply: 'Bewerben',
      edit: 'Bearbeiten',
      cancel: 'Abbrechen',
      viewDetails: 'Details anzeigen',
      loginToSave: 'Anmelden zum Speichern',
      jobSaved: 'Job gespeichert!',
      jobRemovedFromSaved: 'Job aus Gespeichert entfernt',
    },
    home: { aiRecommended: 'KI-empfohlene Jobs', updateProfile: 'Profil aktualisieren', addVideoCv: 'Video-Lebenslauf hinzufügen' },
    jobs: { filters: 'Filter', match: 'Übereinstimmung', whyFits: 'Warum dieser Job zu Ihnen passt', search: 'Suchen', industry: 'Branche', workType: 'Art', experience: 'Erfahrung', sortBy: 'Sortieren' },
    profile: { skills: 'Fähigkeiten', portfolio: 'Portfolio', videoCv: 'Video-Lebenslauf (MP4)' },
    notifications: { title: 'Benachrichtigungen', allCaughtUp: 'Alles erledigt', noNew: 'Keine neuen Benachrichtigungen' },
    login: { welcome: 'Willkommen bei CareerSearch', signIn: 'Melden Sie sich an', iAm: 'Ich bin', candidate: 'Bewerber', recruiter: 'Personalvermittler', email: 'E-Mail', password: 'Passwort', signInBtn: 'Anmelden', noAccount: 'Kein Konto?', invalidCreds: 'Ungültige Anmeldedaten', createAccount: 'Konto erstellen' },
    footer: { blog: 'Blog', pricing: 'Preise', privacy: 'Datenschutz', terms: 'AGB', help: 'Hilfe', contact: 'Kontakt', copyright: 'Smart Job Match' },
  },
  it: {
    theme: { switchTo: 'Cambia tema' },
    nav: {
      home: 'Home',
      jobs: 'Lavori',
      profile: 'Profilo',
      messages: 'Messaggi',
      recruiter: 'Reclutatore',
      blog: 'Blog',
      pricing: 'Prezzi',
      account: 'Account',
      logout: 'Esci',
      signUp: 'Registrati',
      login: 'Accedi',
    },
    common: {
      viewAll: 'Vedi tutto',
      save: 'Salva',
      saved: 'Salvato',
      apply: 'Candidati',
      edit: 'Modifica',
      cancel: 'Annulla',
      viewDetails: 'Vedi dettagli',
      loginToSave: 'Accedi per salvare',
      jobSaved: 'Lavoro salvato!',
      jobRemovedFromSaved: 'Lavoro rimosso dai salvati',
    },
    home: { aiRecommended: 'Lavori consigliati dall\'IA', updateProfile: 'Aggiorna il tuo profilo', addVideoCv: 'Aggiungi video CV' },
    jobs: { filters: 'Filtri', match: 'corrispondenza', whyFits: 'Perché questo lavoro fa per te', search: 'Cerca', industry: 'Settore', workType: 'Tipo', experience: 'Esperienza', sortBy: 'Ordina' },
    profile: { skills: 'Competenze', portfolio: 'Portfolio', videoCv: 'CV video (MP4)' },
    notifications: { title: 'Notifiche', allCaughtUp: 'Sei aggiornato', noNew: 'Nessuna nuova notifica' },
    login: { welcome: 'Benvenuto su CareerSearch', signIn: 'Accedi al tuo account', iAm: 'Sono', candidate: 'Candidato', recruiter: 'Reclutatore', email: 'Email', password: 'Password', signInBtn: 'Accedi', noAccount: 'Non hai un account?', invalidCreds: 'Email o password non validi', createAccount: 'Crea account' },
    footer: { blog: 'Blog', pricing: 'Prezzi', privacy: 'Privacy', terms: 'Termini', help: 'Aiuto', contact: 'Contatto', copyright: 'Smart Job Match' },
    cv: { uploadDocuments: 'Carica documenti', close: 'Chiudi', cvPdf: 'CV (PDF)', videoCvMp4: 'CV video (MP4)', uploadPdfMax: 'Carica il CV in PDF (max 10 MB)', uploading: 'Caricamento...', choosePdf: 'Scegli PDF', uploadMp4OrLink: 'Carica video MP4 o incolla link', chooseMp4: 'Scegli video MP4', or: 'o', pasteVideoUrl: 'Incolla URL video', addLink: 'Aggiungi link', uploadVideoCv: 'Carica CV video (MP4)', updateProfile: 'Aggiorna il tuo profilo', addVideoCvStandOut: 'Aggiungi CV video per distinguerti', uploadCvBetterMatches: 'Carica il CV per migliori corrispondenze', keepCvUpdated: 'Mantieni il CV aggiornato', loginToUpdateCv: 'Accedi per aggiornare', updateCvVideoCv: 'Aggiorna CV / CV video', uploadCv: 'Carica CV', errPdfOnly: 'Carica un file PDF', cvUploaded: 'CV caricato!', errVideoFormat: 'Carica video MP4, WebM o MOV', errEnterUrl: 'Inserisci un URL', errValidUrl: 'Inserisci un URL valido', videoUploaded: 'CV video caricato!', videoLinkAdded: 'Link aggiunto!' },
    trustBadges: { platformStandards: 'Standard della piattaforma', enterpriseSecurity: 'Sicurezza aziendale', gdpr: 'Conformità GDPR', encrypted: 'CV e messaggi crittografati', aiMatching: 'IA testata', mobile: 'Mobile testato', push: 'Notifiche attive', multilang: 'Multilingue', payment: 'Pagamenti integrati', performance: 'Prestazioni testate', readMore: 'Leggi di più' },
    skills: { compatibility: 'Compatibilità competenze', basedOnProfile: 'Basato sul tuo profilo', uploadToSee: 'Carica il CV per vedere le corrispondenze', required: 'Richiesto', uploadToAnalyze: 'Carica il CV per analizzare', profileStrength: 'Forza del profilo', addSkill: 'Aggiungi competenza...' },
    jobDetails: { description: 'Descrizione', requirements: 'Requisiti', benefits: 'Benefici', jobNotFound: 'Lavoro non trovato.', backToJobs: 'Torna ai lavori', featured: 'In evidenza', sponsored: 'Sponsorizzato', jobDescription: 'Descrizione', requiredSkills: 'Competenze richieste', experience: 'Esperienza', posted: 'Pubblicato', deadline: 'Scadenza', whyFits: 'Perché questo lavoro fa per te', advancedAi: 'Analisi IA avanzata', advancedAiPremium: 'Analisi IA (Premium)', skillGap: 'Lacune competenze', salaryBenchmark: 'Stipendio di riferimento', interviewLikelihood: 'Probabilità colloquio', competition: 'Competizione', loginToApply: 'Accedi per candidarti', saveJob: 'Salva lavoro' },
    requireLogin: { title: 'Accesso richiesto', signInToAccess: 'Accedi per continuare', signIn: 'Accedi' },
  },
  pt: {
    theme: { switchTo: 'Mudar tema' },
    nav: {
      home: 'Início',
      jobs: 'Vagas',
      profile: 'Perfil',
      messages: 'Mensagens',
      recruiter: 'Recrutador',
      blog: 'Blog',
      pricing: 'Preços',
      account: 'Conta',
      logout: 'Sair',
      signUp: 'Cadastrar',
      login: 'Entrar',
    },
    common: {
      viewAll: 'Ver tudo',
      save: 'Salvar',
      saved: 'Salvo',
      apply: 'Candidatar',
      edit: 'Editar',
      cancel: 'Cancelar',
      viewDetails: 'Ver detalhes',
      loginToSave: 'Entrar para salvar',
      jobSaved: 'Vaga salva!',
      jobRemovedFromSaved: 'Vaga removida dos salvos',
    },
    home: { aiRecommended: 'Vagas recomendadas por IA', updateProfile: 'Atualize seu perfil', addVideoCv: 'Adicione vídeo CV' },
    jobs: { filters: 'Filtros', match: 'correspondência', whyFits: 'Por que esta vaga combina com você', search: 'Buscar', industry: 'Indústria', workType: 'Tipo', experience: 'Experiência', sortBy: 'Ordenar' },
    profile: { skills: 'Habilidades', portfolio: 'Portfólio', videoCv: 'CV em vídeo (MP4)' },
    notifications: { title: 'Notificações', allCaughtUp: 'Você está em dia', noNew: 'Sem novas notificações' },
    login: { welcome: 'Bem-vindo ao CareerSearch', signIn: 'Entre para acessar', iAm: 'Sou', candidate: 'Candidato', recruiter: 'Recrutador', email: 'E-mail', password: 'Senha', signInBtn: 'Entrar', noAccount: 'Não tem conta?', invalidCreds: 'E-mail ou senha inválidos', createAccount: 'Criar conta' },
    footer: { blog: 'Blog', pricing: 'Preços', privacy: 'Privacidade', terms: 'Termos', help: 'Ajuda', contact: 'Contato', copyright: 'Smart Job Match' },
    cv: { uploadDocuments: 'Enviar documentos', close: 'Fechar', cvPdf: 'CV (PDF)', videoCvMp4: 'CV em vídeo (MP4)', uploadPdfMax: 'Envie seu CV em PDF (máx. 10 MB)', uploading: 'Enviando...', choosePdf: 'Escolher PDF', uploadMp4OrLink: 'Envie vídeo MP4 ou cole um link', chooseMp4: 'Escolher vídeo MP4', or: 'ou', pasteVideoUrl: 'Cole a URL do vídeo', addLink: 'Adicionar link', uploadVideoCv: 'Enviar CV em vídeo (MP4)', updateProfile: 'Atualize seu perfil', addVideoCvStandOut: 'Adicione CV em vídeo para se destacar', uploadCvBetterMatches: 'Envie seu CV para melhores vagas', keepCvUpdated: 'Mantenha seu CV atualizado', loginToUpdateCv: 'Entrar para atualizar', updateCvVideoCv: 'Atualizar CV / CV em vídeo', uploadCv: 'Enviar CV', errPdfOnly: 'Envie um arquivo PDF', cvUploaded: 'CV enviado!', errVideoFormat: 'Envie vídeo MP4, WebM ou MOV', errEnterUrl: 'Digite uma URL', errValidUrl: 'Digite uma URL válida', videoUploaded: 'CV em vídeo enviado!', videoLinkAdded: 'Link adicionado!' },
    trustBadges: { platformStandards: 'Padrões da plataforma', enterpriseSecurity: 'Segurança empresarial', gdpr: 'Conformidade GDPR', encrypted: 'CV e mensagens criptografados', aiMatching: 'IA testada', mobile: 'Mobile testado', push: 'Notificações ativas', multilang: 'Multilíngue', payment: 'Pagamentos integrados', performance: 'Performance testada', readMore: 'Leia mais' },
    skills: { compatibility: 'Compatibilidade de habilidades', basedOnProfile: 'Baseado no seu perfil', uploadToSee: 'Envie seu CV para ver correspondências', required: 'Obrigatório', uploadToAnalyze: 'Envie seu CV para analisar', profileStrength: 'Força do perfil', addSkill: 'Adicionar habilidade...' },
    jobDetails: { description: 'Descrição', requirements: 'Requisitos', benefits: 'Benefícios', jobNotFound: 'Vaga não encontrada.', backToJobs: 'Voltar às vagas', featured: 'Destaque', sponsored: 'Patrocinado', jobDescription: 'Descrição', requiredSkills: 'Habilidades necessárias', experience: 'Experiência', posted: 'Publicado', deadline: 'Prazo', whyFits: 'Por que esta vaga combina com você', advancedAi: 'Análise IA avançada', advancedAiPremium: 'Análise IA (Premium)', skillGap: 'Lacuna de habilidades', salaryBenchmark: 'Referência salarial', interviewLikelihood: 'Probabilidade de entrevista', competition: 'Competição', loginToApply: 'Entrar para candidatar', saveJob: 'Salvar vaga' },
    requireLogin: { title: 'Login necessário', signInToAccess: 'Entre para acessar', signIn: 'Entrar' },
  },
  zh: {
    theme: { switchTo: '切换主题' },
    nav: {
      home: '首页',
      jobs: '职位',
      profile: '个人资料',
      messages: '消息',
      recruiter: '招聘',
      blog: '博客',
      pricing: '价格',
      account: '账户',
      logout: '退出',
      signUp: '注册',
      login: '登录',
    },
    common: {
      viewAll: '查看全部',
      save: '保存',
      saved: '已保存',
      apply: '申请',
      edit: '编辑',
      cancel: '取消',
      viewDetails: '查看详情',
      loginToSave: '登录以保存',
      jobSaved: '职位已保存！',
      jobRemovedFromSaved: '已从保存中移除',
    },
    home: { aiRecommended: 'AI 推荐职位', updateProfile: '更新您的个人资料', addVideoCv: '添加视频简历' },
    jobs: { filters: '筛选', match: '匹配', whyFits: '为什么适合您', search: '搜索', industry: '行业', workType: '类型', experience: '经验', sortBy: '排序' },
    profile: { skills: '技能', portfolio: '作品集', videoCv: '视频简历 (MP4)' },
    notifications: { title: '通知', allCaughtUp: '您已全部了解', noNew: '暂无新通知' },
    login: { welcome: '欢迎使用 CareerSearch', signIn: '登录您的账户', iAm: '我是', candidate: '求职者', recruiter: '招聘方', email: '邮箱', password: '密码', signInBtn: '登录', noAccount: '没有账户？', invalidCreds: '邮箱或密码错误', createAccount: '创建账户' },
    footer: { blog: '博客', pricing: '价格', privacy: '隐私政策', terms: '条款', help: '帮助中心', contact: '联系我们', copyright: '智能职位匹配' },
    cv: { uploadDocuments: '上传文档', close: '关闭', cvPdf: '简历 (PDF)', videoCvMp4: '视频简历 (MP4)', uploadPdfMax: '上传PDF简历（最大10MB）', uploading: '上传中...', choosePdf: '选择PDF文件', uploadMp4OrLink: '上传MP4视频或粘贴链接', chooseMp4: '选择MP4视频', or: '或', pasteVideoUrl: '粘贴视频URL', addLink: '添加链接', uploadVideoCv: '上传视频简历 (MP4)', updateProfile: '更新您的个人资料', addVideoCvStandOut: '添加视频简历脱颖而出', uploadCvBetterMatches: '上传简历获得更好匹配', keepCvUpdated: '保持简历更新', loginToUpdateCv: '登录以更新', updateCvVideoCv: '更新简历 / 视频简历', uploadCv: '上传简历', errPdfOnly: '请上传PDF文件', cvUploaded: '简历已上传！', errVideoFormat: '请上传MP4、WebM或MOV视频', errEnterUrl: '请输入视频URL', errValidUrl: '请输入有效URL', videoUploaded: '视频简历上传成功！', videoLinkAdded: '链接已添加！' },
    trustBadges: { platformStandards: '平台标准', enterpriseSecurity: '企业级安全', gdpr: 'GDPR合规', encrypted: '简历和消息加密', aiMatching: 'AI匹配测试', mobile: '移动端测试', push: '推送通知', multilang: '多语言', payment: '支付集成', performance: '性能测试', readMore: '阅读更多' },
    skills: { compatibility: '技能匹配度', basedOnProfile: '基于您的个人资料', uploadToSee: '上传简历查看匹配', required: '必需', uploadToAnalyze: '上传简历进行分析', profileStrength: '资料完整度', addSkill: '添加技能...' },
    jobDetails: { description: '描述', requirements: '要求', benefits: '福利', jobNotFound: '未找到职位。', backToJobs: '返回职位', featured: '精选', sponsored: '赞助', jobDescription: '职位描述', requiredSkills: '所需技能', experience: '经验', posted: '发布时间', deadline: '截止日期', whyFits: '为什么适合您', advancedAi: '高级AI分析', advancedAiPremium: '高级AI分析（高级版）', skillGap: '技能差距', salaryBenchmark: '薪资参考', interviewLikelihood: '面试可能性', competition: '竞争', loginToApply: '登录申请', saveJob: '保存职位' },
    requireLogin: { title: '需要登录', signInToAccess: '请登录以访问', signIn: '登录' },
  },
  ja: {
    theme: { switchTo: 'テーマを切り替え' },
    nav: {
      home: 'ホーム',
      jobs: '求人',
      profile: 'プロフィール',
      messages: 'メッセージ',
      recruiter: '採用担当',
      blog: 'ブログ',
      pricing: '料金',
      account: 'アカウント',
      logout: 'ログアウト',
      signUp: '新規登録',
      login: 'ログイン',
    },
    common: {
      viewAll: 'すべて見る',
      save: '保存',
      saved: '保存済み',
      apply: '応募',
      edit: '編集',
      cancel: 'キャンセル',
      viewDetails: '詳細を見る',
      loginToSave: '保存するにはログイン',
      jobSaved: '求人を保存しました！',
      jobRemovedFromSaved: '保存から削除しました',
    },
    home: { aiRecommended: 'AIおすすめ求人', updateProfile: 'プロフィールを更新', addVideoCv: 'ビデオ履歴書を追加' },
    jobs: { filters: 'フィルター', match: 'マッチ', whyFits: 'この求人があなたに合う理由', search: '検索', industry: '業界', workType: '勤務形態', experience: '経験', sortBy: '並び替え' },
    profile: { skills: 'スキル', portfolio: 'ポートフォリオ', videoCv: 'ビデオ履歴書 (MP4)' },
    notifications: { title: '通知', allCaughtUp: 'すべて確認済み', noNew: '新しい通知はありません' },
    login: { welcome: 'CareerSearchへようこそ', signIn: 'アカウントにサインイン', iAm: '私は', candidate: '求職者', recruiter: '採用担当', email: 'メール', password: 'パスワード', signInBtn: 'サインイン', noAccount: 'アカウントをお持ちでないですか？', invalidCreds: 'メールまたはパスワードが無効です', createAccount: 'アカウント作成' },
    footer: { blog: 'ブログ', pricing: '料金', privacy: 'プライバシー', terms: '利用規約', help: 'ヘルプ', contact: 'お問い合わせ', copyright: 'スマート求人マッチング' },
    cv: { uploadDocuments: 'ドキュメントをアップロード', close: '閉じる', cvPdf: '履歴書 (PDF)', videoCvMp4: 'ビデオ履歴書 (MP4)', uploadPdfMax: 'PDFで履歴書をアップロード（最大10MB）', uploading: 'アップロード中...', choosePdf: 'PDFを選択', uploadMp4OrLink: 'MP4動画をアップロードまたはリンクを貼り付け', chooseMp4: 'MP4動画を選択', or: 'または', pasteVideoUrl: '動画URLを貼り付け', addLink: 'リンクを追加', uploadVideoCv: 'ビデオ履歴書をアップロード (MP4)', updateProfile: 'プロフィールを更新', addVideoCvStandOut: 'ビデオ履歴書で差をつける', uploadCvBetterMatches: '履歴書をアップロードしてマッチング', keepCvUpdated: '履歴書を最新に保つ', loginToUpdateCv: 'ログインして更新', updateCvVideoCv: '履歴書 / ビデオ履歴書を更新', uploadCv: '履歴書をアップロード', errPdfOnly: 'PDFファイルをアップロードしてください', cvUploaded: '履歴書をアップロードしました！', errVideoFormat: 'MP4、WebM、MOV動画をアップロードしてください', errEnterUrl: 'URLを入力してください', errValidUrl: '有効なURLを入力してください', videoUploaded: 'ビデオ履歴書をアップロードしました！', videoLinkAdded: 'リンクを追加しました！' },
    trustBadges: { platformStandards: 'プラットフォーム基準', enterpriseSecurity: 'エンタープライズセキュリティ', gdpr: 'GDPR準拠', encrypted: '暗号化ストレージ', aiMatching: 'AIマッチングテスト済み', mobile: 'モバイル対応', push: 'プッシュ通知', multilang: '多言語対応', payment: '決済統合', performance: 'パフォーマンステスト済み', readMore: '続きを読む' },
    skills: { compatibility: 'スキル適合度', basedOnProfile: 'プロフィールに基づく', uploadToSee: '履歴書をアップロードしてマッチングを確認', required: '必須', uploadToAnalyze: '履歴書をアップロードして分析', profileStrength: 'プロフィール強度', addSkill: 'スキルを追加...' },
    jobDetails: { description: '説明', requirements: '要件', benefits: '福利厚生', jobNotFound: '求人が見つかりません。', backToJobs: '求人に戻る', featured: '注目', sponsored: 'スポンサー', jobDescription: '職務内容', requiredSkills: '必要なスキル', experience: '経験', posted: '掲載日', deadline: '締め切り', whyFits: 'この求人があなたに合う理由', advancedAi: '高度なAI分析', advancedAiPremium: '高度なAI分析（プレミアム）', skillGap: 'スキルギャップ', salaryBenchmark: '給与ベンチマーク', interviewLikelihood: '面接可能性', competition: '競争', loginToApply: 'ログインして応募', saveJob: '求人を保存' },
    requireLogin: { title: 'ログインが必要', signInToAccess: 'このページにアクセスするにはログインしてください', signIn: 'ログイン' },
  },
  ko: {
    theme: { switchTo: '테마 변경' },
    nav: {
      home: '홈',
      jobs: '채용',
      profile: '프로필',
      messages: '메시지',
      recruiter: '채용 담당',
      blog: '블로그',
      pricing: '가격',
      account: '계정',
      logout: '로그아웃',
      signUp: '가입',
      login: '로그인',
    },
    common: {
      viewAll: '전체 보기',
      save: '저장',
      saved: '저장됨',
      apply: '지원',
      edit: '편집',
      cancel: '취소',
      viewDetails: '상세 보기',
      loginToSave: '저장하려면 로그인',
      jobSaved: '채용 공고 저장됨!',
      jobRemovedFromSaved: '저장에서 제거됨',
    },
    home: { aiRecommended: 'AI 추천 채용', updateProfile: '프로필 업데이트', addVideoCv: '영상 이력서 추가' },
    jobs: { filters: '필터', match: '매칭', whyFits: '이 채용이 당신에게 맞는 이유', search: '검색', industry: '산업', workType: '근무 형태', experience: '경력', sortBy: '정렬' },
    profile: { skills: '스킬', portfolio: '포트폴리오', videoCv: '영상 이력서 (MP4)' },
    notifications: { title: '알림', allCaughtUp: '모두 확인했습니다', noNew: '새 알림 없음' },
    login: { welcome: 'CareerSearch에 오신 것을 환영합니다', signIn: '계정에 로그인하세요', iAm: '저는', candidate: '구직자', recruiter: '채용 담당', email: '이메일', password: '비밀번호', signInBtn: '로그인', noAccount: '계정이 없으신가요?', invalidCreds: '이메일 또는 비밀번호가 올바르지 않습니다', createAccount: '계정 만들기' },
    footer: { blog: '블로그', pricing: '가격', privacy: '개인정보', terms: '이용약관', help: '도움말', contact: '문의', copyright: '스마트 채용 매칭' },
    cv: { uploadDocuments: '문서 업로드', close: '닫기', cvPdf: '이력서 (PDF)', videoCvMp4: '영상 이력서 (MP4)', uploadPdfMax: 'PDF 이력서 업로드 (최대 10MB)', uploading: '업로드 중...', choosePdf: 'PDF 선택', uploadMp4OrLink: 'MP4 영상 업로드 또는 링크 붙여넣기', chooseMp4: 'MP4 영상 선택', or: '또는', pasteVideoUrl: '영상 URL 붙여넣기', addLink: '링크 추가', uploadVideoCv: '영상 이력서 업로드 (MP4)', updateProfile: '프로필 업데이트', addVideoCvStandOut: '영상 이력서로 돋보이기', uploadCvBetterMatches: '이력서 업로드하여 매칭', keepCvUpdated: '이력서 최신 유지', loginToUpdateCv: '로그인하여 업데이트', updateCvVideoCv: '이력서 / 영상 이력서 업데이트', uploadCv: '이력서 업로드', errPdfOnly: 'PDF 파일을 업로드하세요', cvUploaded: '이력서 업로드됨!', errVideoFormat: 'MP4, WebM, MOV 영상을 업로드하세요', errEnterUrl: 'URL을 입력하세요', errValidUrl: '유효한 URL을 입력하세요', videoUploaded: '영상 이력서 업로드됨!', videoLinkAdded: '링크 추가됨!' },
    trustBadges: { platformStandards: '플랫폼 기준', enterpriseSecurity: '엔터프라이즈 보안', gdpr: 'GDPR 준수', encrypted: '암호화된 저장소', aiMatching: 'AI 매칭 테스트', mobile: '모바일 대응', push: '푸시 알림', multilang: '다국어', payment: '결제 통합', performance: '성능 테스트', readMore: '더 읽기' },
    skills: { compatibility: '스킬 호환성', basedOnProfile: '프로필 기반', uploadToSee: '이력서 업로드하여 매칭 확인', required: '필수', uploadToAnalyze: '이력서 업로드하여 분석', profileStrength: '프로필 강도', addSkill: '스킬 추가...' },
    jobDetails: { description: '설명', requirements: '요구사항', benefits: '혜택', jobNotFound: '채용을 찾을 수 없습니다.', backToJobs: '채용으로 돌아가기', featured: '추천', sponsored: '스폰서', jobDescription: '직무 설명', requiredSkills: '필요 스킬', experience: '경력', posted: '게시일', deadline: '마감일', whyFits: '이 채용이 당신에게 맞는 이유', advancedAi: '고급 AI 분석', advancedAiPremium: '고급 AI 분석 (프리미엄)', skillGap: '스킬 격차', salaryBenchmark: '급여 벤치마크', interviewLikelihood: '면접 가능성', competition: '경쟁', loginToApply: '로그인하여 지원', saveJob: '채용 저장' },
    requireLogin: { title: '로그인 필요', signInToAccess: '이 페이지에 접근하려면 로그인하세요', signIn: '로그인' },
  },
  ar: {
    theme: { switchTo: 'تغيير السمة' },
    nav: {
      home: 'الرئيسية',
      jobs: 'وظائف',
      profile: 'الملف الشخصي',
      messages: 'الرسائل',
      recruiter: 'المُوظّف',
      blog: 'المدونة',
      pricing: 'الأسعار',
      account: 'الحساب',
      logout: 'تسجيل الخروج',
      signUp: 'التسجيل',
      login: 'تسجيل الدخول',
    },
    common: {
      viewAll: 'عرض الكل',
      save: 'حفظ',
      saved: 'محفوظ',
      apply: 'تقدم',
      edit: 'تعديل',
      cancel: 'إلغاء',
      viewDetails: 'عرض التفاصيل',
      loginToSave: 'تسجيل الدخول للحفظ',
      jobSaved: 'تم حفظ الوظيفة!',
      jobRemovedFromSaved: 'تمت إزالة الوظيفة من المحفوظات',
    },
    home: { aiRecommended: 'وظائف موصى بها بالذكاء الاصطناعي', updateProfile: 'تحديث ملفك الشخصي', addVideoCv: 'أضف فيديو السيرة الذاتية' },
    jobs: { filters: 'تصفية', match: 'تطابق', whyFits: 'لماذا تناسبك هذه الوظيفة', search: 'بحث', industry: 'الصناعة', workType: 'نوع العمل', experience: 'الخبرة', sortBy: 'ترتيب' },
    profile: { skills: 'المهارات', portfolio: 'الأعمال', videoCv: 'فيديو السيرة الذاتية (MP4)' },
    notifications: { title: 'الإشعارات', allCaughtUp: 'لقد اطلعت على كل شيء', noNew: 'لا توجد إشعارات جديدة' },
    login: { welcome: 'مرحباً بك في CareerSearch', signIn: 'سجّل الدخول للوصول', iAm: 'أنا', candidate: 'مرشح', recruiter: 'موظف توظيف', email: 'البريد', password: 'كلمة المرور', signInBtn: 'تسجيل الدخول', noAccount: 'ليس لديك حساب؟', invalidCreds: 'البريد أو كلمة المرور غير صحيحة', createAccount: 'إنشاء حساب' },
    footer: { blog: 'المدونة', pricing: 'الأسعار', privacy: 'الخصوصية', terms: 'الشروط', help: 'المساعدة', contact: 'اتصل', copyright: 'مطابقة الوظائف الذكية' },
    cv: { uploadDocuments: 'تحميل المستندات', close: 'إغلاق', cvPdf: 'السيرة الذاتية (PDF)', videoCvMp4: 'فيديو السيرة الذاتية (MP4)', uploadPdfMax: 'حمّل سيرتك الذاتية بصيغة PDF (حتى 10 ميجابايت)', uploading: 'جاري التحميل...', choosePdf: 'اختر ملف PDF', uploadMp4OrLink: 'حمّل فيديو MP4 أو الصق رابطاً', chooseMp4: 'اختر فيديو MP4', or: 'أو', pasteVideoUrl: 'الصق رابط الفيديو', addLink: 'إضافة رابط', uploadVideoCv: 'تحميل فيديو السيرة الذاتية (MP4)', updateProfile: 'تحديث ملفك الشخصي', addVideoCvStandOut: 'أضف فيديو السيرة الذاتية للتميز', uploadCvBetterMatches: 'حمّل سيرتك الذاتية للمطابقات', keepCvUpdated: 'حافظ على تحديث سيرتك', loginToUpdateCv: 'تسجيل الدخول للتحديث', updateCvVideoCv: 'تحديث السيرة / فيديو السيرة', uploadCv: 'تحميل السيرة الذاتية', errPdfOnly: 'يرجى تحميل ملف PDF', cvUploaded: 'تم تحميل السيرة الذاتية!', errVideoFormat: 'يرجى تحميل فيديو MP4 أو WebM أو MOV', errEnterUrl: 'يرجى إدخال رابط', errValidUrl: 'يرجى إدخال رابط صالح', videoUploaded: 'تم تحميل فيديو السيرة الذاتية!', videoLinkAdded: 'تم إضافة الرابط!' },
    trustBadges: { platformStandards: 'معايير المنصة', enterpriseSecurity: 'أمان على مستوى المؤسسات', gdpr: 'متوافق مع GDPR', encrypted: 'تخزين مشفر', aiMatching: 'مطابقة الذكاء الاصطناعي', mobile: 'استجابة للجوال', push: 'إشعارات نشطة', multilang: 'متعدد اللغات', payment: 'نظام دفع متكامل', performance: 'اختبار الأداء', readMore: 'اقرأ المزيد' },
    skills: { compatibility: 'توافق المهارات', basedOnProfile: 'بناءً على ملفك الشخصي', uploadToSee: 'حمّل سيرتك لرؤية المطابقات', required: 'مطلوب', uploadToAnalyze: 'حمّل سيرتك للتحليل', profileStrength: 'قوة الملف الشخصي', addSkill: 'إضافة مهارة...' },
    jobDetails: { description: 'الوصف', requirements: 'المتطلبات', benefits: 'المزايا', jobNotFound: 'لم يتم العثور على الوظيفة.', backToJobs: 'العودة للوظائف', featured: 'مميز', sponsored: 'مدعوم', jobDescription: 'وصف الوظيفة', requiredSkills: 'المهارات المطلوبة', experience: 'الخبرة', posted: 'تاريخ النشر', deadline: 'الموعد النهائي', whyFits: 'لماذا تناسبك هذه الوظيفة', advancedAi: 'تحليلات الذكاء الاصطناعي المتقدمة', advancedAiPremium: 'تحليلات الذكاء الاصطناعي (بريميوم)', skillGap: 'فجوة المهارات', salaryBenchmark: 'مرجع الراتب', interviewLikelihood: 'احتمال المقابلة', competition: 'المنافسة', loginToApply: 'تسجيل الدخول للتقديم', saveJob: 'حفظ الوظيفة' },
    requireLogin: { title: 'تسجيل الدخول مطلوب', signInToAccess: 'يرجى تسجيل الدخول للوصول', signIn: 'تسجيل الدخول' },
  },
  ru: {
    theme: { switchTo: 'Сменить тему' },
    nav: {
      home: 'Главная',
      jobs: 'Вакансии',
      profile: 'Профиль',
      messages: 'Сообщения',
      recruiter: 'Рекрутер',
      blog: 'Блог',
      pricing: 'Цены',
      account: 'Аккаунт',
      logout: 'Выйти',
      signUp: 'Регистрация',
      login: 'Войти',
    },
    common: {
      viewAll: 'Смотреть всё',
      save: 'Сохранить',
      saved: 'Сохранено',
      apply: 'Откликнуться',
      edit: 'Редактировать',
      cancel: 'Отмена',
      viewDetails: 'Подробнее',
      loginToSave: 'Войдите, чтобы сохранить',
      jobSaved: 'Вакансия сохранена!',
      jobRemovedFromSaved: 'Удалено из сохранённых',
    },
    home: { aiRecommended: 'Вакансии по рекомендации ИИ', updateProfile: 'Обновите профиль', addVideoCv: 'Добавьте видео-резюме' },
    jobs: { filters: 'Фильтры', match: 'совпадение', whyFits: 'Почему эта вакансия вам подходит', search: 'Поиск', industry: 'Отрасль', workType: 'Тип', experience: 'Опыт', sortBy: 'Сортировка' },
    profile: { skills: 'Навыки', portfolio: 'Портфолио', videoCv: 'Видео-резюме (MP4)' },
    notifications: { title: 'Уведомления', allCaughtUp: 'Всё просмотрено', noNew: 'Нет новых уведомлений' },
    login: { welcome: 'Добро пожаловать в CareerSearch', signIn: 'Войдите в аккаунт', iAm: 'Я', candidate: 'Кандидат', recruiter: 'Рекрутер', email: 'Email', password: 'Пароль', signInBtn: 'Войти', noAccount: 'Нет аккаунта?', invalidCreds: 'Неверный email или пароль', createAccount: 'Создать аккаунт' },
    footer: { blog: 'Блог', pricing: 'Цены', privacy: 'Конфиденциальность', terms: 'Условия', help: 'Помощь', contact: 'Контакты', copyright: 'Умный подбор вакансий' },
    cv: { uploadDocuments: 'Загрузить документы', close: 'Закрыть', cvPdf: 'Резюме (PDF)', videoCvMp4: 'Видео-резюме (MP4)', uploadPdfMax: 'Загрузите резюме в PDF (макс. 10 МБ)', uploading: 'Загрузка...', choosePdf: 'Выбрать PDF', uploadMp4OrLink: 'Загрузите MP4 или вставьте ссылку', chooseMp4: 'Выбрать MP4', or: 'или', pasteVideoUrl: 'Вставьте URL видео', addLink: 'Добавить ссылку', uploadVideoCv: 'Загрузить видео-резюме (MP4)', updateProfile: 'Обновите профиль', addVideoCvStandOut: 'Добавьте видео-резюме', uploadCvBetterMatches: 'Загрузите резюме для подбора', keepCvUpdated: 'Держите резюме обновлённым', loginToUpdateCv: 'Войдите для обновления', updateCvVideoCv: 'Обновить резюме / видео-резюме', uploadCv: 'Загрузить резюме', errPdfOnly: 'Загрузите файл PDF', cvUploaded: 'Резюме загружено!', errVideoFormat: 'Загрузите MP4, WebM или MOV', errEnterUrl: 'Введите URL', errValidUrl: 'Введите корректный URL', videoUploaded: 'Видео-резюме загружено!', videoLinkAdded: 'Ссылка добавлена!' },
    trustBadges: { platformStandards: 'Стандарты платформы', enterpriseSecurity: 'Безопасность и надёжность', gdpr: 'Соответствие GDPR', encrypted: 'Шифрование данных', aiMatching: 'ИИ проверен', mobile: 'Мобильная версия', push: 'Уведомления', multilang: 'Мультиязычность', payment: 'Платежи', performance: 'Тестирование', readMore: 'Подробнее' },
    skills: { compatibility: 'Совместимость навыков', basedOnProfile: 'На основе профиля', uploadToSee: 'Загрузите резюме для анализа', required: 'Обязательно', uploadToAnalyze: 'Загрузите резюме', profileStrength: 'Сила профиля', addSkill: 'Добавить навык...' },
    jobDetails: { description: 'Описание', requirements: 'Требования', benefits: 'Преимущества', jobNotFound: 'Вакансия не найдена.', backToJobs: 'Назад к вакансиям', featured: 'Рекомендуем', sponsored: 'Спонсор', jobDescription: 'Описание', requiredSkills: 'Требуемые навыки', experience: 'Опыт', posted: 'Опубликовано', deadline: 'Срок', whyFits: 'Почему эта вакансия вам подходит', advancedAi: 'Расширенный анализ ИИ', advancedAiPremium: 'Анализ ИИ (Премиум)', skillGap: 'Разрыв навыков', salaryBenchmark: 'Зарплата', interviewLikelihood: 'Вероятность собеседования', competition: 'Конкуренция', loginToApply: 'Войти для отклика', saveJob: 'Сохранить' },
    requireLogin: { title: 'Требуется вход', signInToAccess: 'Войдите для доступа', signIn: 'Войти' },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      return localStorage.getItem(LANG_STORAGE_KEY) || 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem(LANG_STORAGE_KEY, lang);
      document.documentElement.lang = lang;
      document.documentElement.dir = ['ar'].includes(lang) ? 'rtl' : 'ltr';
    } catch (e) {}
  }, [lang]);

  const t = (path) => {
    const keys = path.split('.');
    let obj = translations[lang] || en;
    for (const k of keys) {
      obj = obj?.[k];
    }
    if (obj != null) return obj;
    obj = en;
    for (const k of keys) {
      obj = obj?.[k];
    }
    return obj ?? path;
  };

  const value = { lang, setLang, t, translations: translations[lang] || en };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
